name: wakatime-stats

on:
  schedule:
    - cron: '0 6 * * *' # setiap jam 13:00 WIB
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          COMMIT_BY_ME: "False"
          COMMIT_MESSAGE: "🧮 Updated dev metrics"
          COMMIT_USERNAME: "novaka-dev"
          COMMIT_EMAIL: "you@example.com"
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "False"
          SHOW_PROJECTS: "True"
          SHOW_LANGUAGE: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_COMMIT: "True"
          SHOW_UPDATED_DATE: "True"
          SHOW_SHORT_INFO: "True"
