name: Waka Weekly

on:
  schedule:
    - cron: '45 5 * * *' # 12:45 siang WIB
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          TIME_RANGE: last_7_days
          LANG_COUNT: 7
          SHOW_TIME: true
          SHOW_TOTAL: false
          SECTION_NAME: "waka-weekly"
